export const TEST_STORE = 'TEST_STORE';
export const SET_LOADING = 'SET_LOADING';
export const CANCEL_LOADING = 'CANCEL_LOADING';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REGISTRATION_FORM_MODAL = 'REG_FORM_MODAL'
export const LOGIN_FORM_MODAL = 'LOG_FORM_MODAL'
