export const TEST_STORE = 'TEST_STORE';
export const SET_LOADING = 'SET_LOADING';
export const CANCEL_LOADING = 'CANCEL_LOADING';
export const ADD_TO_CART = 'ADD_TO_CART';
export const SHOW_LOGIN_MODAL = 'SHOW_LOGIN_MODAL';
export const HIDE_LOGIN_MODAL = 'HIDE_LOGIN_MODAL';